export const valueLabels: Record<string, Record<string, string>> = {
  strategy_type: {
    arbitrage: 'Арбитраж',
    fundamental: 'Фундаментальная',
    speculative: 'Спекулятивная',
    mixed: 'Смешанная',
    carry: 'Кэрри',
    stat: 'Стат',
  },
  basket: {
    fundamental: 'Фундаментальная',
    speculative: 'Спекулятивная',
    arbitrage: 'Арбитраж',
  },
  price_mode: {
    BIDASK: 'Bid/Ask',
    OHLC: 'OHLC',
    AUTO: 'Авто',
    bidask: 'Bid/Ask',
    ohlc: 'OHLC',
    auto: 'Авто',
  },
  capital_base_mode: {
    FULL_CASH: 'Полный кэш',
    MARGIN_AWARE: 'С учётом маржи',
    full_cash: 'Полный кэш',
    margin_aware: 'С учётом маржи',
  },
  cadence: {
    daily: 'Ежедневно',
    weekly: 'Еженедельно',
    monthly: 'Ежемесячно',
    none: 'Нет',
    DAILY: 'Ежедневно',
    WEEKLY: 'Еженедельно',
    MONTHLY: 'Ежемесячно',
    NONE: 'Нет',
  },
  day_count: {
    'ACT/365': 'ACT/365',
    'ACT/360': 'ACT/360',
  },
  action: {
    approve: 'Одобрить',
    reject: 'Отклонить',
    hold: 'Удержать',
    enter: 'Вход',
    exit: 'Выход',
  },
  risk_state: {
    green: 'Зелёный',
    yellow: 'Жёлтый',
    red: 'Красный',
  },
  news_severity: {
    low: 'Низкая',
    medium: 'Средняя',
    high: 'Высокая',
    critical: 'Критическая',
  },
  signal_action: {
    enter: 'Вход',
    exit: 'Выход',
    hold: 'Держать',
  },
  signal_direction: {
    cash_and_carry: 'Кэш-энд-кэрри',
    reverse: 'Реверс',
    neutral: 'Нейтрально',
  },
  signal_reasons: {
    enter_ok: 'Вход разрешён',
    skip_floor: 'Пропуск: floor',
    skip_liquidity: 'Пропуск: ликвидность',
    skip_score: 'Пропуск: скор',
    floor_fail: 'Floor не пройден',
    liquidity_fail: 'Ликвидность не пройдена',
    entry_filter_fail: 'Фильтр входа не пройден',
    dte_too_low: 'Слишком мало дней до экспирации',
    hold: 'Держать',
    tp: 'TP',
    sl: 'SL',
    time: 'Таймстоп',
    expiry: 'Близко к экспирации',
    implied_rate_above_required: 'Имплайд ставка выше требуемой',
    implied_rate_below_required: 'Имплайд ставка ниже требуемой',
    implied_rate_neutral: 'Имплайд ставка нейтральна',
    insufficient_history: 'Недостаточно истории',
    zscore_high: 'Z-score высокий',
    zscore_low: 'Z-score низкий',
    zscore_revert: 'Z-score вернулся',
    zscore_mid: 'Z-score в зоне ожидания',
    event_filter_blocked: 'Заблокировано фильтром событий',
    direction_conflict: 'Конфликт направлений',
    stat_not_confirmed: 'Стат-сигнал не подтверждён',
    carry_not_confirmed: 'Carry-сигнал не подтверждён',
  },
  direction: {
    cash_and_carry: 'Кэш-энд-кэрри',
    reverse: 'Реверс',
    neutral: 'Нейтрально',
  },
  decision: {
    ENTER_OK: 'Вход разрешён',
    SKIP_FLOOR: 'Пропуск: floor',
    SKIP_LIQUIDITY: 'Пропуск: ликвидность',
    SKIP_SCORE: 'Пропуск: скор',
    enter_ok: 'Вход разрешён',
    skip_floor: 'Пропуск: floor',
    skip_liquidity: 'Пропуск: ликвидность',
    skip_score: 'Пропуск: скор',
  },
  proposal_type: {
    rebalance: 'Ребалансировка',
    confirm: 'Подтверждение',
  },
  side: {
    buy: 'Покупка',
    sell: 'Продажа',
  },
  exit_reason: {
    TP: 'TP',
    SL: 'SL',
    TRAIL: 'Трейлинг',
  },
  status: {
    ok: 'ок',
    queued: 'в очереди',
    ready: 'готово',
    recorded: 'записано',
    filled: 'исполнено',
    failed: 'ошибка',
    cancelled: 'отменено',
    pending: 'ожидание',
    running: 'в работе',
    stub: 'заглушка',
  },
}
