export const valueLabels: Record<string, Record<string, string>> = {
  strategy_type: {
    arbitrage: 'Арбитраж',
    fundamental: 'Фундаментальная',
    speculative: 'Спекулятивная',
    mixed: 'Смешанная',
    carry: 'Кэрри',
    stat: 'Статистическая',
  },
  basket: {
    fundamental: 'Фундаментальная',
    speculative: 'Спекулятивная',
    arbitrage: 'Арбитраж',
  },
  price_mode: {
    BIDASK: 'Bid/Ask',
    OHLC: 'OHLC',
    AUTO: 'Авто',
    bidask: 'Bid/Ask',
    ohlc: 'OHLC',
    auto: 'Авто',
  },
  capital_base_mode: {
    FULL_CASH: 'Полный кэш',
    MARGIN_AWARE: 'С учетом маржи',
    full_cash: 'Полный кэш',
    margin_aware: 'С учетом маржи',
  },
  cadence: {
    daily: 'Ежедневно',
    weekly: 'Еженедельно',
    monthly: 'Ежемесячно',
    none: 'Нет',
    DAILY: 'Ежедневно',
    WEEKLY: 'Еженедельно',
    MONTHLY: 'Ежемесячно',
    NONE: 'Нет',
  },
  day_count: {
    'ACT/365': 'ACT/365',
    'ACT/360': 'ACT/360',
  },
  action: {
    approve: 'Одобрить',
    reject: 'Отклонить',
    hold: 'Удерживать',
    enter: 'Вход',
    exit: 'Выход',
  },
  risk_state: {
    green: 'Зеленый',
    yellow: 'Желтый',
    red: 'Красный',
  },
  news_severity: {
    low: 'Низкая',
    medium: 'Средняя',
    high: 'Высокая',
    critical: 'Критическая',
  },
  signal_action: {
    enter: 'Вход',
    exit: 'Выход',
    hold: 'Держать',
    hold_open: 'Open position (hold)',
  },
  signal_action_effective: {
    enter: 'Вход разрешен',
    exit: 'Выход',
    hold: 'Держать',
    hold_pretrade: 'Вход заблокирован pre-trade',
    check_pretrade: 'Ожидает pre-trade проверки',
    hold_open: 'Open position (hold)',
  },
  signal_direction: {
    cash_and_carry: 'Кэш-энд-кэрри',
    reverse: 'Реверс',
    neutral: 'Нейтрально',
  },
  forecast_model: {
    half_life_capped: 'Half-life (ограничен H)',
    h_max_days: 'H_max_days (time-stop)',
  },
  signal_reasons: {
    enter_ok: 'Вход разрешен',
    skip_floor: 'Пропуск: floor',
    skip_liquidity: 'Пропуск: ликвидность',
    skip_orderbook: 'Пропуск: стакан',
    skip_score: 'Пропуск: скор',
    floor_fail: 'Floor не пройден',
    liquidity_fail: 'Ликвидность не пройдена',
    entry_filter_fail: 'Фильтр входа не пройден',
    dte_too_low: 'Слишком мало дней до экспирации',
    hold: 'Держать',
    tp: 'TP',
    sl: 'SL',
    time: 'Таймстоп',
    expiry: 'Близко к экспирации',
    implied_rate_above_required: 'Имплайд ставка выше требуемой',
    implied_rate_below_required: 'Имплайд ставка ниже требуемой',
    implied_rate_neutral: 'Имплайд ставка нейтральна',
    insufficient_history: 'Недостаточно истории',
    zscore_high: 'Z-score высокий',
    zscore_low: 'Z-score низкий',
    zscore_revert: 'Z-score вернулся',
    zscore_mid: 'Z-score в зоне ожидания',
    event_filter_blocked: 'Заблокировано фильтром событий',
    direction_conflict: 'Конфликт направлений',
    stat_not_confirmed: 'Стат-сигнал не подтвержден',
    carry_not_confirmed: 'Carry-сигнал не подтвержден',
  },
  orderbook_reasons: {
    orderbook_intraday_disabled: 'Интрадей отключен',
    orderbook_stock_missing: 'Нет котировок акции',
    orderbook_fut_missing: 'Нет котировок фьючерса',
    orderbook_stock_depth: 'Недостаточная глубина акции',
    orderbook_fut_depth: 'Недостаточная глубина фьючерса',
    orderbook_stock_stale: 'Старая котировка акции',
    orderbook_fut_stale: 'Старая котировка фьючерса',
    orderbook_stock_imbalance: 'Дисбаланс стакана акции',
    orderbook_fut_imbalance: 'Дисбаланс стакана фьючерса',
  },
  orderbook_data_warnings: {
    orderbook_stock_quote_missing: 'Нет котировки акции в ISS',
    orderbook_fut_quote_missing: 'Нет котировки фьючерса в ISS',
    orderbook_stock_depth_missing: 'Нет глубины стакана акции',
    orderbook_fut_depth_missing: 'Нет глубины стакана фьючерса',
  },
  pretrade_reasons: {
    stock_quote_missing: 'Нет котировки акции в коридоре',
    fut_quote_missing: 'Нет котировки фьючерса в коридоре',
    stock_range_miss: 'Цена акции вне коридора',
    fut_range_miss: 'Цена фьючерса вне коридора',
    spread_out_of_band: 'Спред вне коридора',
    snapshot_unsynced: 'Несинхронные снапшоты ног',
    stock_volume_miss: 'Недостаточный объем акции',
    fut_volume_miss: 'Недостаточный объем фьючерса',
  },
  pretrade_status: {
    PLACE: 'Готово к выставлению',
    CHECK: 'Нужна перепроверка',
    BLOCK: 'Блокировка',
  },
  direction: {
    cash_and_carry: 'Кэш-энд-кэрри',
    reverse: 'Реверс',
    neutral: 'Нейтрально',
  },
  decision: {
    ENTER_OK: 'Вход разрешен',
    SKIP_FLOOR: 'Пропуск: floor',
    SKIP_LIQUIDITY: 'Пропуск: ликвидность',
    SKIP_ORDERBOOK: 'Пропуск: стакан',
    SKIP_SCORE: 'Пропуск: скор',
    enter_ok: 'Вход разрешен',
    skip_floor: 'Пропуск: floor',
    skip_liquidity: 'Пропуск: ликвидность',
    skip_orderbook: 'Пропуск: стакан',
    skip_score: 'Пропуск: скор',
  },
  proposal_type: {
    rebalance: 'Ребалансировка',
    confirm: 'Подтверждение',
  },
  side: {
    buy: 'Покупка',
    sell: 'Продажа',
    stock: 'Акция',
    future: 'Фьючерс',
    'акция': 'Акция',
    'фьючерс': 'Фьючерс',
  },
  exit_reason: {
    TP: 'TP',
    SL: 'SL',
    TRAIL: 'Трейлинг',
  },
  status: {
    ok: 'ОК',
    queued: 'В очереди',
    ready: 'Готово',
    recorded: 'Записано',
    filled: 'Исполнено',
    failed: 'Ошибка',
    cancelled: 'Отменено',
    pending: 'Ожидание',
    running: 'В работе',
    stub: 'Заглушка',
  },
}
