from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CommodityEntity:
    node: str
    role: str
    canonical: str
    aliases: tuple[str, ...]


@dataclass(frozen=True)
class DependencyEdge:
    source: str
    target: str


@dataclass(frozen=True)
class CommodityKnowledge:
    commodity: str
    entities: tuple[CommodityEntity, ...]
    edges: tuple[DependencyEdge, ...]
    event_query_terms: tuple[str, ...]

def _entity(node: str, role: str, canonical: str, *aliases: str) -> CommodityEntity:
    return CommodityEntity(node=node, role=role, canonical=canonical, aliases=tuple(aliases))


COMMODITY_KNOWLEDGE: dict[str, CommodityKnowledge] = {
    "BRN": CommodityKnowledge(
        commodity="BRN",
        entities=(
            _entity("producer:opec", "producer", "OPEC+", "opec", "opec+", "producer group"),
            _entity("exporter:saudi_arabia", "exporter", "Saudi Arabia", "saudi arabia", "saudi", "ksa", "aramco"),
            _entity("exporter:russia", "exporter", "Russia", "russia", "russian exports"),
            _entity("exporter:iraq", "exporter", "Iraq", "iraq", "iraqi oil"),
            _entity("exporter:uae", "exporter", "UAE", "uae", "united arab emirates", "abu dhabi"),
            _entity("exporter:kuwait", "exporter", "Kuwait", "kuwait"),
            _entity("exporter:iran", "exporter", "Iran", "iran", "iranian crude"),
            _entity("importer:china", "importer", "China", "china", "chinese refiners"),
            _entity("importer:india", "importer", "India", "india", "indian refiners"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu"),
            _entity("chokepoint:hormuz", "chokepoint", "Strait of Hormuz", "strait of hormuz", "hormuz"),
            _entity("chokepoint:suez", "chokepoint", "Suez Canal", "suez canal", "suez"),
            _entity("chokepoint:bab_el_mandeb", "chokepoint", "Bab el-Mandeb", "bab el-mandeb", "red sea lane"),
            _entity("regulator:us_treasury", "regulator", "US Treasury", "us treasury", "ofac", "sanctions office"),
        ),
        edges=(
            DependencyEdge("chokepoint:hormuz", "flow:seaborne_crude"),
            DependencyEdge("chokepoint:suez", "flow:seaborne_crude"),
            DependencyEdge("chokepoint:bab_el_mandeb", "flow:seaborne_crude"),
            DependencyEdge("exporter:saudi_arabia", "flow:seaborne_crude"),
            DependencyEdge("exporter:russia", "flow:seaborne_crude"),
            DependencyEdge("exporter:iraq", "flow:seaborne_crude"),
            DependencyEdge("exporter:uae", "flow:seaborne_crude"),
            DependencyEdge("exporter:kuwait", "flow:seaborne_crude"),
            DependencyEdge("exporter:iran", "flow:seaborne_crude"),
            DependencyEdge("producer:opec", "flow:seaborne_crude"),
            DependencyEdge("importer:china", "flow:crude_demand"),
            DependencyEdge("importer:india", "flow:crude_demand"),
            DependencyEdge("importer:eu", "flow:crude_demand"),
            DependencyEdge("flow:seaborne_crude", "commodity:BRN"),
            DependencyEdge("flow:crude_demand", "commodity:BRN"),
            DependencyEdge("regulator:us_treasury", "flow:seaborne_crude"),
        ),
        event_query_terms=(
            "strait of hormuz",
            "suez canal",
            "bab el-mandeb",
            "shipping halted",
            "hormuz blockade",
            "export ban",
            "sanctions",
            "opec output cut",
            "israel strikes iran",
            "oil facility attack",
            "pipeline outage",
            "terminal restart",
            "official statement",
        ),
    ),
    "NG_US": CommodityKnowledge(
        commodity="NG_US",
        entities=(
            _entity("producer:appalachia", "producer", "Appalachia", "appalachia", "marcellus", "utica"),
            _entity("producer:haynesville", "producer", "Haynesville", "haynesville"),
            _entity("producer:permian", "producer", "Permian", "permian", "associated gas"),
            _entity("terminal:freeport", "terminal", "Freeport LNG", "freeport lng", "freeport terminal"),
            _entity("terminal:sabine", "terminal", "Sabine Pass LNG", "sabine pass", "cheniere"),
            _entity("terminal:corpus", "terminal", "Corpus Christi LNG", "corpus christi lng"),
            _entity("terminal:cameron", "terminal", "Cameron LNG", "cameron lng"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu gas buyers"),
            _entity("importer:japan", "importer", "Japan", "japan", "japanese buyers"),
            _entity("importer:korea", "importer", "South Korea", "south korea", "korean buyers"),
            _entity("importer:china", "importer", "China", "china", "chinese lng"),
            _entity("chokepoint:panama", "chokepoint", "Panama Canal", "panama canal", "panama transit"),
            _entity("chokepoint:hormuz", "chokepoint", "Strait of Hormuz", "strait of hormuz", "hormuz"),
            _entity("operator:eia", "operator", "EIA", "eia", "storage report"),
        ),
        edges=(
            DependencyEdge("producer:appalachia", "flow:us_gas_supply"),
            DependencyEdge("producer:haynesville", "flow:us_gas_supply"),
            DependencyEdge("producer:permian", "flow:us_gas_supply"),
            DependencyEdge("terminal:freeport", "flow:us_lng_exports"),
            DependencyEdge("terminal:sabine", "flow:us_lng_exports"),
            DependencyEdge("terminal:corpus", "flow:us_lng_exports"),
            DependencyEdge("terminal:cameron", "flow:us_lng_exports"),
            DependencyEdge("chokepoint:panama", "flow:lng_shipping"),
            DependencyEdge("chokepoint:hormuz", "flow:lng_shipping"),
            DependencyEdge("importer:eu", "flow:lng_import_demand"),
            DependencyEdge("importer:japan", "flow:lng_import_demand"),
            DependencyEdge("importer:korea", "flow:lng_import_demand"),
            DependencyEdge("importer:china", "flow:lng_import_demand"),
            DependencyEdge("flow:us_gas_supply", "commodity:NG_US"),
            DependencyEdge("flow:us_lng_exports", "commodity:NG_US"),
            DependencyEdge("flow:lng_shipping", "commodity:NG_US"),
            DependencyEdge("flow:lng_import_demand", "commodity:NG_US"),
            DependencyEdge("operator:eia", "commodity:NG_US"),
        ),
        event_query_terms=(
            "freeport lng",
            "sabine pass",
            "panama canal",
            "terminal outage",
            "terminal restart",
            "storage report",
            "freeze-off",
            "pipeline outage",
            "import surge",
            "official statement",
        ),
    ),
    "GOLD": CommodityKnowledge(
        commodity="GOLD",
        entities=(
            _entity("producer:china", "producer", "China", "china mine output", "china gold"),
            _entity("producer:australia", "producer", "Australia", "australia", "australian gold"),
            _entity("producer:russia", "producer", "Russia", "russia", "russian gold"),
            _entity("producer:canada", "producer", "Canada", "canada", "canadian gold"),
            _entity("importer:india", "importer", "India", "india", "indian jewelry demand"),
            _entity("importer:china", "importer", "China", "china", "chinese jewelry demand"),
            _entity("importer:turkey", "importer", "Turkey", "turkey", "turkish gold imports"),
            _entity("operator:fed", "operator", "Federal Reserve", "federal reserve", "fed"),
            _entity("operator:ecb", "operator", "ECB", "ecb", "european central bank"),
            _entity("operator:pboc", "operator", "PBoC", "pboc", "people's bank of china"),
            _entity("operator:central_banks", "operator", "Central Banks", "central bank buying", "reserve purchases"),
        ),
        edges=(
            DependencyEdge("operator:fed", "flow:real_yields"),
            DependencyEdge("operator:ecb", "flow:real_yields"),
            DependencyEdge("operator:pboc", "flow:real_yields"),
            DependencyEdge("operator:central_banks", "flow:physical_gold_demand"),
            DependencyEdge("importer:india", "flow:physical_gold_demand"),
            DependencyEdge("importer:china", "flow:physical_gold_demand"),
            DependencyEdge("importer:turkey", "flow:physical_gold_demand"),
            DependencyEdge("producer:china", "flow:mine_supply"),
            DependencyEdge("producer:australia", "flow:mine_supply"),
            DependencyEdge("producer:russia", "flow:mine_supply"),
            DependencyEdge("producer:canada", "flow:mine_supply"),
            DependencyEdge("flow:real_yields", "commodity:GOLD"),
            DependencyEdge("flow:physical_gold_demand", "commodity:GOLD"),
            DependencyEdge("flow:mine_supply", "commodity:GOLD"),
        ),
        event_query_terms=(
            "central bank buying",
            "fed rate cut",
            "real yields",
            "reserve purchases",
            "official statement",
            "sanctions",
            "safe haven demand",
            "mine disruption",
            "import surge",
            "policy meeting",
        ),
    ),
    "SILVER": CommodityKnowledge(
        commodity="SILVER",
        entities=(
            _entity("producer:mexico", "producer", "Mexico", "mexico", "mexican mines"),
            _entity("producer:peru", "producer", "Peru", "peru", "peruvian mines"),
            _entity("producer:china", "producer", "China", "china", "chinese mines"),
            _entity("producer:chile", "producer", "Chile", "chile", "chilean mines"),
            _entity("importer:china", "importer", "China", "china", "chinese industrial demand"),
            _entity("importer:india", "importer", "India", "india", "indian silver imports"),
            _entity("importer:usa", "importer", "United States", "united states", "us industrial demand"),
            _entity("operator:solar", "operator", "Solar Manufacturers", "solar demand", "pv demand"),
            _entity("operator:electronics", "operator", "Electronics Sector", "electronics demand"),
            _entity("operator:auto", "operator", "EV Supply Chain", "ev demand", "battery demand"),
        ),
        edges=(
            DependencyEdge("producer:mexico", "flow:silver_mine_supply"),
            DependencyEdge("producer:peru", "flow:silver_mine_supply"),
            DependencyEdge("producer:china", "flow:silver_mine_supply"),
            DependencyEdge("producer:chile", "flow:silver_mine_supply"),
            DependencyEdge("importer:china", "flow:industrial_silver_demand"),
            DependencyEdge("importer:india", "flow:industrial_silver_demand"),
            DependencyEdge("importer:usa", "flow:industrial_silver_demand"),
            DependencyEdge("operator:solar", "flow:industrial_silver_demand"),
            DependencyEdge("operator:electronics", "flow:industrial_silver_demand"),
            DependencyEdge("operator:auto", "flow:industrial_silver_demand"),
            DependencyEdge("flow:silver_mine_supply", "commodity:SILVER"),
            DependencyEdge("flow:industrial_silver_demand", "commodity:SILVER"),
        ),
        event_query_terms=(
            "solar demand",
            "electronics demand",
            "mine disruption",
            "smelter outage",
            "import surge",
            "output cut",
            "sanctions",
            "official statement",
            "supply disruption",
            "manufacturing rebound",
        ),
    ),
    "PLATINUM": CommodityKnowledge(
        commodity="PLATINUM",
        entities=(
            _entity("producer:south_africa", "producer", "South Africa", "south africa", "rsa platinum"),
            _entity("producer:russia", "producer", "Russia", "russia", "russian pgm"),
            _entity("producer:zimbabwe", "producer", "Zimbabwe", "zimbabwe"),
            _entity("importer:china", "importer", "China", "china", "chinese auto demand"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu"),
            _entity("operator:auto", "operator", "Auto Catalysts", "autocatalyst", "vehicle catalyst"),
        ),
        edges=(
            DependencyEdge("producer:south_africa", "flow:pgm_supply"),
            DependencyEdge("producer:russia", "flow:pgm_supply"),
            DependencyEdge("producer:zimbabwe", "flow:pgm_supply"),
            DependencyEdge("importer:china", "flow:autocatalyst_demand"),
            DependencyEdge("importer:eu", "flow:autocatalyst_demand"),
            DependencyEdge("operator:auto", "flow:autocatalyst_demand"),
            DependencyEdge("flow:pgm_supply", "commodity:PLATINUM"),
            DependencyEdge("flow:autocatalyst_demand", "commodity:PLATINUM"),
        ),
        event_query_terms=(
            "south africa mine strike",
            "pgm supply",
            "platinum deficit",
            "autocatalyst demand",
            "smelter outage",
            "official statement",
        ),
    ),
    "PALLADIUM": CommodityKnowledge(
        commodity="PALLADIUM",
        entities=(
            _entity("producer:russia", "producer", "Russia", "russia", "norilsk", "russian palladium"),
            _entity("producer:south_africa", "producer", "South Africa", "south africa", "rsa pgm"),
            _entity("producer:canada", "producer", "Canada", "canada"),
            _entity("importer:china", "importer", "China", "china", "chinese auto demand"),
            _entity("importer:usa", "importer", "United States", "united states", "us auto demand"),
            _entity("operator:auto", "operator", "Auto Catalysts", "autocatalyst", "catalyst demand"),
            _entity("regulator:us_treasury", "regulator", "US Treasury", "sanctions", "us treasury", "ofac"),
        ),
        edges=(
            DependencyEdge("producer:russia", "flow:palladium_supply"),
            DependencyEdge("producer:south_africa", "flow:palladium_supply"),
            DependencyEdge("producer:canada", "flow:palladium_supply"),
            DependencyEdge("importer:china", "flow:autocatalyst_demand"),
            DependencyEdge("importer:usa", "flow:autocatalyst_demand"),
            DependencyEdge("operator:auto", "flow:autocatalyst_demand"),
            DependencyEdge("regulator:us_treasury", "flow:palladium_supply"),
            DependencyEdge("flow:palladium_supply", "commodity:PALLADIUM"),
            DependencyEdge("flow:autocatalyst_demand", "commodity:PALLADIUM"),
        ),
        event_query_terms=(
            "russian palladium",
            "norilsk disruption",
            "pgm sanctions",
            "autocatalyst demand",
            "mine outage",
            "official statement",
        ),
    ),
    "COPPER": CommodityKnowledge(
        commodity="COPPER",
        entities=(
            _entity("producer:chile", "producer", "Chile", "chile", "codelco", "escondida", "el teniente", "zaldivar"),
            _entity("producer:peru", "producer", "Peru", "peru"),
            _entity("producer:drc", "producer", "DR Congo", "congo", "drc"),
            _entity("importer:china", "importer", "China", "china", "chinese demand"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu"),
            _entity("operator:smelter", "operator", "Copper Smelters", "smelter", "treatment charges"),
        ),
        edges=(
            DependencyEdge("producer:chile", "flow:copper_mine_supply"),
            DependencyEdge("producer:peru", "flow:copper_mine_supply"),
            DependencyEdge("producer:drc", "flow:copper_mine_supply"),
            DependencyEdge("operator:smelter", "flow:copper_mine_supply"),
            DependencyEdge("importer:china", "flow:refined_copper_demand"),
            DependencyEdge("importer:eu", "flow:refined_copper_demand"),
            DependencyEdge("flow:copper_mine_supply", "commodity:COPPER"),
            DependencyEdge("flow:refined_copper_demand", "commodity:COPPER"),
        ),
        event_query_terms=(
            "copper mine strike",
            "codelco output",
            "escondida",
            "smelter cut",
            "treatment charges",
            "china stimulus",
        ),
    ),
    "ALUMINUM": CommodityKnowledge(
        commodity="ALUMINUM",
        entities=(
            _entity("producer:china", "producer", "China", "china", "chinese smelters"),
            _entity("producer:russia", "producer", "Russia", "russia", "rusal"),
            _entity("producer:india", "producer", "India", "india"),
            _entity("producer:qatar", "producer", "Qatar", "qatar", "qatalum"),
            _entity("producer:bahrain", "producer", "Bahrain", "bahrain"),
            _entity("producer:guinea", "producer", "Guinea", "guinea", "bauxite"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu"),
            _entity("importer:usa", "importer", "United States", "united states", "us"),
            _entity("operator:smelter_power", "operator", "Smelter Power", "power curbs", "electricity tariffs"),
        ),
        edges=(
            DependencyEdge("producer:china", "flow:aluminum_smelter_supply"),
            DependencyEdge("producer:russia", "flow:aluminum_smelter_supply"),
            DependencyEdge("producer:india", "flow:aluminum_smelter_supply"),
            DependencyEdge("operator:smelter_power", "flow:aluminum_smelter_supply"),
            DependencyEdge("importer:eu", "flow:aluminum_demand"),
            DependencyEdge("importer:usa", "flow:aluminum_demand"),
            DependencyEdge("flow:aluminum_smelter_supply", "commodity:ALUMINUM"),
            DependencyEdge("flow:aluminum_demand", "commodity:ALUMINUM"),
        ),
        event_query_terms=(
            "aluminum smelter outage",
            "power curbs",
            "bauxite supply",
            "alumina disruption",
            "output cut",
            "official statement",
        ),
    ),
    "NICKEL": CommodityKnowledge(
        commodity="NICKEL",
        entities=(
            _entity(
                "producer:indonesia",
                "producer",
                "Indonesia",
                "indonesia",
                "nickel ore",
                "morowali",
                "vale indonesia",
                "eramet",
            ),
            _entity("producer:philippines", "producer", "Philippines", "philippines", "nickel ore"),
            _entity("producer:russia", "producer", "Russia", "russia", "norilsk nickel"),
            _entity("importer:china", "importer", "China", "china", "stainless steel demand"),
            _entity("operator:battery", "operator", "Battery Supply Chain", "battery demand", "ev demand"),
            _entity("operator:stainless", "operator", "Stainless Steel", "stainless steel"),
        ),
        edges=(
            DependencyEdge("producer:indonesia", "flow:nickel_ore_supply"),
            DependencyEdge("producer:philippines", "flow:nickel_ore_supply"),
            DependencyEdge("producer:russia", "flow:nickel_ore_supply"),
            DependencyEdge("importer:china", "flow:nickel_demand"),
            DependencyEdge("operator:battery", "flow:nickel_demand"),
            DependencyEdge("operator:stainless", "flow:nickel_demand"),
            DependencyEdge("flow:nickel_ore_supply", "commodity:NICKEL"),
            DependencyEdge("flow:nickel_demand", "commodity:NICKEL"),
        ),
        event_query_terms=(
            "indonesia nickel policy",
            "ore export ban",
            "permit volume slashed",
            "production quota",
            "nickel project ramp",
            "morowali operations",
            "stainless steel demand",
            "battery demand",
            "official statement",
        ),
    ),
    "ZINC": CommodityKnowledge(
        commodity="ZINC",
        entities=(
            _entity("producer:china", "producer", "China", "china", "chinese zinc"),
            _entity("producer:peru", "producer", "Peru", "peru"),
            _entity("producer:australia", "producer", "Australia", "australia"),
            _entity("importer:china", "importer", "China", "china"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu"),
            _entity("operator:smelter", "operator", "Zinc Smelters", "zinc smelter", "treatment charges"),
        ),
        edges=(
            DependencyEdge("producer:china", "flow:zinc_mine_supply"),
            DependencyEdge("producer:peru", "flow:zinc_mine_supply"),
            DependencyEdge("producer:australia", "flow:zinc_mine_supply"),
            DependencyEdge("operator:smelter", "flow:zinc_mine_supply"),
            DependencyEdge("importer:china", "flow:zinc_demand"),
            DependencyEdge("importer:eu", "flow:zinc_demand"),
            DependencyEdge("flow:zinc_mine_supply", "commodity:ZINC"),
            DependencyEdge("flow:zinc_demand", "commodity:ZINC"),
        ),
        event_query_terms=(
            "zinc smelter outage",
            "zinc mine disruption",
            "treatment charges",
            "inventory draw",
            "galvanized steel demand",
            "official statement",
        ),
    ),
    "WHEAT": CommodityKnowledge(
        commodity="WHEAT",
        entities=(
            _entity("producer:russia", "producer", "Russia", "russia wheat", "russian wheat exports"),
            _entity("producer:ukraine", "producer", "Ukraine", "ukraine wheat", "ukrainian grain"),
            _entity("producer:usa", "producer", "United States", "us wheat", "usda"),
            _entity("producer:eu", "producer", "European Union", "eu wheat", "europe wheat"),
            _entity("importer:egypt", "importer", "Egypt", "egypt", "gasc"),
            _entity("importer:turkey", "importer", "Turkey", "turkey"),
            _entity("importer:indonesia", "importer", "Indonesia", "indonesia"),
            _entity("chokepoint:black_sea", "chokepoint", "Black Sea Corridor", "black sea corridor", "grain corridor"),
        ),
        edges=(
            DependencyEdge("producer:russia", "flow:wheat_export_supply"),
            DependencyEdge("producer:ukraine", "flow:wheat_export_supply"),
            DependencyEdge("producer:usa", "flow:wheat_export_supply"),
            DependencyEdge("producer:eu", "flow:wheat_export_supply"),
            DependencyEdge("chokepoint:black_sea", "flow:wheat_export_supply"),
            DependencyEdge("importer:egypt", "flow:wheat_import_demand"),
            DependencyEdge("importer:turkey", "flow:wheat_import_demand"),
            DependencyEdge("importer:indonesia", "flow:wheat_import_demand"),
            DependencyEdge("flow:wheat_export_supply", "commodity:WHEAT"),
            DependencyEdge("flow:wheat_import_demand", "commodity:WHEAT"),
        ),
        event_query_terms=(
            "black sea wheat",
            "grain corridor",
            "export ban",
            "crop condition",
            "drought",
            "usda report",
        ),
    ),
    "SUGAR": CommodityKnowledge(
        commodity="SUGAR",
        entities=(
            _entity("producer:brazil", "producer", "Brazil", "brazil sugar", "center-south brazil"),
            _entity("producer:india", "producer", "India", "india sugar"),
            _entity("producer:thailand", "producer", "Thailand", "thailand sugar"),
            _entity("importer:china", "importer", "China", "china sugar imports"),
            _entity("importer:indonesia", "importer", "Indonesia", "indonesia sugar"),
            _entity("operator:ethanol", "operator", "Ethanol Blend", "ethanol parity", "ethanol mandate"),
        ),
        edges=(
            DependencyEdge("producer:brazil", "flow:sugar_export_supply"),
            DependencyEdge("producer:india", "flow:sugar_export_supply"),
            DependencyEdge("producer:thailand", "flow:sugar_export_supply"),
            DependencyEdge("operator:ethanol", "flow:sugar_export_supply"),
            DependencyEdge("importer:china", "flow:sugar_import_demand"),
            DependencyEdge("importer:indonesia", "flow:sugar_import_demand"),
            DependencyEdge("flow:sugar_export_supply", "commodity:SUGAR"),
            DependencyEdge("flow:sugar_import_demand", "commodity:SUGAR"),
        ),
        event_query_terms=(
            "brazil sugar cane",
            "india export quota",
            "ethanol parity",
            "monsoon",
            "crop downgrade",
            "official statement",
        ),
    ),
    "COFFEE": CommodityKnowledge(
        commodity="COFFEE",
        entities=(
            _entity("producer:brazil", "producer", "Brazil", "brazil coffee", "arabica", "conab", "conilon"),
            _entity("producer:vietnam", "producer", "Vietnam", "vietnam coffee", "robusta", "cecafe"),
            _entity("producer:colombia", "producer", "Colombia", "colombia coffee"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu demand"),
            _entity("importer:usa", "importer", "United States", "us demand", "united states"),
            _entity("operator:weather", "operator", "Weather Risk", "frost", "drought", "rainfall"),
        ),
        edges=(
            DependencyEdge("producer:brazil", "flow:coffee_export_supply"),
            DependencyEdge("producer:vietnam", "flow:coffee_export_supply"),
            DependencyEdge("producer:colombia", "flow:coffee_export_supply"),
            DependencyEdge("operator:weather", "flow:coffee_export_supply"),
            DependencyEdge("importer:eu", "flow:coffee_import_demand"),
            DependencyEdge("importer:usa", "flow:coffee_import_demand"),
            DependencyEdge("flow:coffee_export_supply", "commodity:COFFEE"),
            DependencyEdge("flow:coffee_import_demand", "commodity:COFFEE"),
        ),
        event_query_terms=(
            "arabica crop",
            "robusta crop",
            "coffee frost",
            "coffee drought",
            "conab coffee harvest",
            "brazil rains coffee crop",
            "harvest outlook",
            "official statement",
        ),
    ),
    "COCOA": CommodityKnowledge(
        commodity="COCOA",
        entities=(
            _entity("producer:ivory_coast", "producer", "Ivory Coast", "ivory coast", "cote d'ivoire", "ccc"),
            _entity("producer:ghana", "producer", "Ghana", "ghana", "cocobod", "cmc"),
            _entity("producer:nigeria", "producer", "Nigeria", "nigeria"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu grinders"),
            _entity("importer:usa", "importer", "United States", "united states", "us grinders"),
            _entity("operator:weather", "operator", "Weather Risk", "harmattan", "heavy rain", "disease"),
        ),
        edges=(
            DependencyEdge("producer:ivory_coast", "flow:cocoa_export_supply"),
            DependencyEdge("producer:ghana", "flow:cocoa_export_supply"),
            DependencyEdge("producer:nigeria", "flow:cocoa_export_supply"),
            DependencyEdge("operator:weather", "flow:cocoa_export_supply"),
            DependencyEdge("importer:eu", "flow:cocoa_processing_demand"),
            DependencyEdge("importer:usa", "flow:cocoa_processing_demand"),
            DependencyEdge("flow:cocoa_export_supply", "commodity:COCOA"),
            DependencyEdge("flow:cocoa_processing_demand", "commodity:COCOA"),
        ),
        event_query_terms=(
            "ivory coast cocoa",
            "ghana cocoa",
            "cocobod farmgate price",
            "cocoa arrivals",
            "harmattan",
            "crop disease",
            "port arrivals",
            "official statement",
        ),
    ),
    "ORANGE": CommodityKnowledge(
        commodity="ORANGE",
        entities=(
            _entity("producer:brazil", "producer", "Brazil", "brazil orange", "sao paulo crop"),
            _entity("producer:usa", "producer", "United States", "florida orange", "usda citrus"),
            _entity("importer:eu", "importer", "European Union", "europe", "eu juice demand"),
            _entity("operator:weather", "operator", "Weather Risk", "hurricane", "frost", "citrus greening"),
        ),
        edges=(
            DependencyEdge("producer:brazil", "flow:orange_juice_supply"),
            DependencyEdge("producer:usa", "flow:orange_juice_supply"),
            DependencyEdge("operator:weather", "flow:orange_juice_supply"),
            DependencyEdge("importer:eu", "flow:orange_juice_demand"),
            DependencyEdge("flow:orange_juice_supply", "commodity:ORANGE"),
            DependencyEdge("flow:orange_juice_demand", "commodity:ORANGE"),
        ),
        event_query_terms=(
            "orange juice futures",
            "citrus greening",
            "florida orange crop",
            "brazil orange crop",
            "hurricane damage",
            "official statement",
        ),
    ),
}
