from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class CausalRule:
    bucket: str
    event: str
    transmission_channel: str
    direction_bias: str
    weight: float
    terms: tuple[str, ...]


GLOBAL_RULES: tuple[CausalRule, ...] = (
    CausalRule(
        bucket="trade_policy",
        event="export_restriction",
        transmission_channel="physical_supply",
        direction_bias="up",
        weight=0.95,
        terms=(
            "export ban",
            "export curb",
            "export quota",
            "export duty",
            "sanctions",
            "embargo",
        ),
    ),
    CausalRule(
        bucket="demand",
        event="import_demand_surge",
        transmission_channel="physical_demand",
        direction_bias="up",
        weight=0.85,
        terms=(
            "import surge",
            "import demand rises",
            "china imports",
            "india imports",
            "refinery runs rise",
        ),
    ),
    CausalRule(
        bucket="demand",
        event="import_demand_drop",
        transmission_channel="physical_demand",
        direction_bias="down",
        weight=0.85,
        terms=(
            "import demand slowdown",
            "demand destruction",
            "import cuts",
            "manufacturing contraction",
            "recession risk",
        ),
    ),
    CausalRule(
        bucket="logistics",
        event="transport_disruption",
        transmission_channel="transport_costs",
        direction_bias="up",
        weight=0.9,
        terms=(
            "port closure",
            "shipping disruption",
            "red sea",
            "suez",
            "hormuz",
            "pipeline outage",
            "rail disruption",
            "canal congestion",
        ),
    ),
    CausalRule(
        bucket="weather",
        event="extreme_weather_supply_shock",
        transmission_channel="weather_supply",
        direction_bias="up",
        weight=0.75,
        terms=(
            "hurricane",
            "storm",
            "flood",
            "freeze",
            "heatwave",
            "drought",
            "wildfire",
        ),
    ),
    CausalRule(
        bucket="monetary_policy",
        event="central_bank_dovish_shift",
        transmission_channel="rates_fx",
        direction_bias="up",
        weight=0.92,
        terms=(
            "rate cut",
            "dovish",
            "qe",
            "liquidity easing",
            "real yields fall",
        ),
    ),
    CausalRule(
        bucket="monetary_policy",
        event="central_bank_hawkish_shift",
        transmission_channel="rates_fx",
        direction_bias="down",
        weight=0.92,
        terms=(
            "rate hike",
            "hawkish",
            "tightening",
            "real yields rise",
            "balance sheet runoff",
        ),
    ),
)


COMMODITY_RULES: dict[str, tuple[CausalRule, ...]] = {
    "BRN": (
        CausalRule(
            bucket="supply",
            event="opec_supply_cut",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=1.0,
            terms=("opec cut", "output cut", "production cut", "voluntary cut"),
        ),
        CausalRule(
            bucket="supply",
            event="opec_supply_increase",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.95,
            terms=("opec increase", "output increase", "production hike", "supply increase"),
        ),
        CausalRule(
            bucket="inventory",
            event="inventory_draw",
            transmission_channel="inventory_balance",
            direction_bias="up",
            weight=0.9,
            terms=("inventory draw", "stocks draw", "crude draw", "eia draw"),
        ),
        CausalRule(
            bucket="inventory",
            event="inventory_build",
            transmission_channel="inventory_balance",
            direction_bias="down",
            weight=0.9,
            terms=("inventory build", "stocks build", "crude build", "eia build"),
        ),
        CausalRule(
            bucket="geopolitics",
            event="middle_east_supply_risk",
            transmission_channel="geopolitical_risk",
            direction_bias="up",
            weight=1.0,
            terms=("iran", "missile", "drone attack", "shipping lane risk", "strait of hormuz"),
        ),
    ),
    "NG_US": (
        CausalRule(
            bucket="weather",
            event="cold_weather_demand",
            transmission_channel="weather_demand",
            direction_bias="up",
            weight=1.0,
            terms=("colder", "cold blast", "hdd", "freeze-off", "polar vortex"),
        ),
        CausalRule(
            bucket="weather",
            event="warm_weather_demand_drop",
            transmission_channel="weather_demand",
            direction_bias="down",
            weight=1.0,
            terms=("warmer", "mild weather", "cooling demand drop", "hdd miss"),
        ),
        CausalRule(
            bucket="inventory",
            event="storage_withdrawal",
            transmission_channel="inventory_balance",
            direction_bias="up",
            weight=0.95,
            terms=("storage withdrawal", "draw larger than expected", "eia withdrawal"),
        ),
        CausalRule(
            bucket="inventory",
            event="storage_injection",
            transmission_channel="inventory_balance",
            direction_bias="down",
            weight=0.95,
            terms=("storage injection", "build larger than expected", "eia injection"),
        ),
        CausalRule(
            bucket="lng",
            event="lng_export_outage",
            transmission_channel="export_flow",
            direction_bias="down",
            weight=0.85,
            terms=("lng outage", "export terminal outage", "freeport outage"),
        ),
        CausalRule(
            bucket="lng",
            event="lng_export_restart",
            transmission_channel="export_flow",
            direction_bias="up",
            weight=0.85,
            terms=("lng restart", "export terminal restart", "lng flows rise"),
        ),
    ),
    "GOLD": (
        CausalRule(
            bucket="monetary_policy",
            event="real_yield_decline",
            transmission_channel="rates_fx",
            direction_bias="up",
            weight=1.0,
            terms=("real yields fall", "treasury yields fall", "rate cuts priced"),
        ),
        CausalRule(
            bucket="monetary_policy",
            event="real_yield_rise",
            transmission_channel="rates_fx",
            direction_bias="down",
            weight=1.0,
            terms=("real yields rise", "treasury yields rise", "hawkish fed"),
        ),
        CausalRule(
            bucket="fx",
            event="usd_weakness",
            transmission_channel="fx_pass_through",
            direction_bias="up",
            weight=0.9,
            terms=("dollar weak", "usd weaker", "dxy falls"),
        ),
        CausalRule(
            bucket="fx",
            event="usd_strength",
            transmission_channel="fx_pass_through",
            direction_bias="down",
            weight=0.9,
            terms=("dollar stronger", "usd stronger", "dxy rises"),
        ),
        CausalRule(
            bucket="safe_haven",
            event="risk_off_geopolitics",
            transmission_channel="risk_appetite",
            direction_bias="up",
            weight=0.95,
            terms=("safe haven demand", "safe-haven demand", "risk-off", "geopolitical escalation", "war risk"),
        ),
    ),
    "SILVER": (
        CausalRule(
            bucket="industrial_demand",
            event="manufacturing_upturn",
            transmission_channel="industrial_cycle",
            direction_bias="up",
            weight=0.9,
            terms=("manufacturing rebound", "pmi rises", "solar demand", "electronics demand"),
        ),
        CausalRule(
            bucket="industrial_demand",
            event="manufacturing_slowdown",
            transmission_channel="industrial_cycle",
            direction_bias="down",
            weight=0.9,
            terms=("manufacturing slowdown", "pmi contraction", "industrial demand weak"),
        ),
        CausalRule(
            bucket="supply",
            event="mine_supply_disruption",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=0.85,
            terms=("mine disruption", "strike", "smelter outage", "supply disruption"),
        ),
    ),
    "PLATINUM": (
        CausalRule(
            bucket="supply",
            event="pgm_mine_disruption",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=0.9,
            terms=("south africa mine strike", "pgm mine outage", "pgm supply disruption", "mine shutdown"),
        ),
        CausalRule(
            bucket="demand",
            event="autocatalyst_demand_drop",
            transmission_channel="industrial_demand",
            direction_bias="down",
            weight=0.82,
            terms=("autocatalyst demand weak", "auto demand slowdown", "vehicle production cuts"),
        ),
    ),
    "PALLADIUM": (
        CausalRule(
            bucket="supply",
            event="russian_palladium_supply_risk",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=0.92,
            terms=("russian palladium sanctions", "norilsk disruption", "palladium supply risk"),
        ),
        CausalRule(
            bucket="demand",
            event="autocatalyst_demand_drop",
            transmission_channel="industrial_demand",
            direction_bias="down",
            weight=0.82,
            terms=("autocatalyst demand weak", "auto demand slowdown", "vehicle production cuts"),
        ),
    ),
    "COPPER": (
        CausalRule(
            bucket="supply",
            event="copper_mine_disruption",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=0.94,
            terms=(
                "codelco mine strike",
                "escondida outage",
                "copper mine disruption",
                "smelter feed disrupted",
                "mine output cut",
            ),
        ),
        CausalRule(
            bucket="supply",
            event="copper_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.84,
            terms=("mine restart", "output guidance raised", "smelter throughput recovers"),
        ),
    ),
    "ALUMINUM": (
        CausalRule(
            bucket="supply",
            event="smelter_power_disruption",
            transmission_channel="energy_cost",
            direction_bias="up",
            weight=0.94,
            terms=(
                "power curbs",
                "aluminum smelter outage",
                "natural gas shortage",
                "force majeure",
                "controlled shutdown",
            ),
        ),
        CausalRule(
            bucket="supply",
            event="aluminum_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.8,
            terms=("smelter restart", "power curbs eased", "aluminum output recovers"),
        ),
    ),
    "NICKEL": (
        CausalRule(
            bucket="trade_policy",
            event="nickel_ore_export_restriction",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=0.95,
            terms=(
                "ore export ban",
                "permit volume slashed",
                "production quota cut",
                "indonesia nickel policy tightens",
            ),
        ),
        CausalRule(
            bucket="supply",
            event="nickel_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.8,
            terms=("quota increase", "nickel project ramp-up", "supply expansion"),
        ),
    ),
    "ZINC": (
        CausalRule(
            bucket="supply",
            event="zinc_smelter_disruption",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=0.9,
            terms=("zinc smelter outage", "treatment charges plunge", "zinc mine disruption"),
        ),
        CausalRule(
            bucket="supply",
            event="zinc_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.8,
            terms=("zinc smelter restart", "mine output recovers", "inventory rebuild"),
        ),
    ),
    "WHEAT": (
        CausalRule(
            bucket="trade_policy",
            event="grain_export_restriction",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=0.96,
            terms=("wheat export ban", "grain corridor disruption", "black sea closure", "export quota"),
        ),
        CausalRule(
            bucket="supply",
            event="wheat_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.82,
            terms=("crop condition improves", "harvest outlook improves", "grain corridor reopened"),
        ),
    ),
    "SUGAR": (
        CausalRule(
            bucket="trade_policy",
            event="sugar_export_restriction",
            transmission_channel="physical_supply",
            direction_bias="up",
            weight=0.9,
            terms=("india sugar export curb", "sugar export quota cut", "sugar export ban", "ethanol parity rises"),
        ),
        CausalRule(
            bucket="supply",
            event="sugar_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.8,
            terms=("cane crush rises", "sugar export quota expanded", "ethanol parity eases"),
        ),
    ),
    "COFFEE": (
        CausalRule(
            bucket="weather",
            event="coffee_crop_weather_shock",
            transmission_channel="weather_supply",
            direction_bias="up",
            weight=0.9,
            terms=("coffee frost", "coffee drought", "arabica crop damage", "robusta crop damage"),
        ),
        CausalRule(
            bucket="supply",
            event="coffee_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.88,
            terms=(
                "record coffee harvest",
                "crop prospects improve",
                "brazil rains bolster crop",
                "arabica output increase",
                "robusta output increase",
            ),
        ),
    ),
    "COCOA": (
        CausalRule(
            bucket="weather",
            event="cocoa_crop_shock",
            transmission_channel="weather_supply",
            direction_bias="up",
            weight=0.92,
            terms=("harmattan", "crop disease", "cocoa arrivals fall", "ivory coast cocoa shortfall"),
        ),
        CausalRule(
            bucket="supply",
            event="cocoa_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.84,
            terms=(
                "farmgate cocoa price cut",
                "cuts farmgate cocoa price",
                "ghana cuts farmgate cocoa price",
                "cocobod financing",
                "cocoa arrivals rise",
                "cocoa output recovers",
                "financing improves",
            ),
        ),
    ),
    "ORANGE": (
        CausalRule(
            bucket="weather",
            event="citrus_crop_shock",
            transmission_channel="weather_supply",
            direction_bias="up",
            weight=0.9,
            terms=("citrus greening", "hurricane damage", "frost", "orange crop loss"),
        ),
        CausalRule(
            bucket="supply",
            event="citrus_supply_recovery",
            transmission_channel="physical_supply",
            direction_bias="down",
            weight=0.8,
            terms=("orange crop recovery", "weather improves", "harvest increase"),
        ),
    ),
}


