from __future__ import annotations

SYMBOL_TOPIC_KEYWORDS: dict[str, tuple[str, ...]] = {
    "NG_US": (
        "natural gas",
        "lng",
        "henry hub",
        "eia storage",
        "pipeline",
        "freeze",
        "hdd",
        "cdd",
        "weather",
    ),
    "BRN": (
        "brent",
        "oil",
        "opec",
        "crude",
        "inventory",
        "stocks",
        "red sea",
        "hormuz",
        "sanctions",
    ),
    "GOLD": (
        "gold",
        "bullion",
        "fed",
        "fomc",
        "yield",
        "dxy",
        "safe haven",
        "inflation",
        "treasury",
    ),
    "SILVER": (
        "silver",
        "xag",
        "solar demand",
        "electronics demand",
        "silver mine",
        "smelter",
        "industrial demand",
    ),
    "PLATINUM": (
        "platinum",
        "xpt",
        "pgm",
        "south africa mine",
        "autocatalyst",
        "mine strike",
    ),
    "PALLADIUM": (
        "palladium",
        "xpd",
        "pgm",
        "russian supply",
        "autocatalyst",
        "mine disruption",
    ),
    "COPPER": (
        "copper",
        "mine strike",
        "smelter",
        "treatment charges",
        "china demand",
        "inventory draw",
    ),
    "ALUMINUM": (
        "aluminum",
        "aluminium",
        "bauxite",
        "alumina",
        "smelter",
        "power curbs",
    ),
    "NICKEL": (
        "nickel",
        "indonesia nickel",
        "ore ban",
        "stainless steel",
        "battery demand",
    ),
    "ZINC": (
        "zinc",
        "zinc smelter",
        "treatment charges",
        "mine output",
        "inventory",
    ),
    "WHEAT": (
        "wheat",
        "black sea wheat",
        "crop condition",
        "drought",
        "frost",
        "export ban",
    ),
    "SUGAR": (
        "sugar",
        "raw sugar",
        "sugar cane",
        "ethanol parity",
        "brazil sugar",
        "india sugar export",
    ),
    "COFFEE": (
        "coffee",
        "arabica",
        "robusta",
        "coffee crop",
        "frost",
        "drought",
    ),
    "COCOA": (
        "cocoa",
        "ivory coast cocoa",
        "ghana cocoa",
        "harmattan",
        "crop disease",
    ),
    "ORANGE": (
        "orange juice",
        "fcoj",
        "citrus greening",
        "florida crop",
        "hurricane",
    ),
}

GLOBAL_CONTEXT_KEYWORDS: tuple[str, ...] = (
    "iran",
    "israel",
    "ukraine",
    "russia",
    "china",
    "middle east",
    "attack",
    "strike",
    "conflict",
    "war",
    "sanction",
    "suez",
    "panama canal",
)

VALID_ASSET_CODE_BY_SYMBOL: dict[str, str] = {
    "BRN": "BR",
    "GOLD": "GOLD",
    "NG_US": "NG",
    "SILVER": "SILV",
    "PLATINUM": "PLT",
    "PALLADIUM": "PLD",
    "COPPER": "COPPER",
    "ALUMINUM": "ALUM",
    "NICKEL": "NICKEL",
    "ZINC": "ZINC",
    "WHEAT": "WHEAT",
    "SUGAR": "SUGAR",
    "COFFEE": "COFFEE",
    "COCOA": "COCOA",
    "ORANGE": "ORANGE",
}
